FROM node:18-alpine as build
WORKDIR /app
COPY frontend/package*.json /app/
RUN npm ci --no-audit --no-fund
COPY frontend /app
ARG VITE_API_BASE
ENV VITE_API_BASE=${VITE_API_BASE}
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


